name: magnet_cnn_no_int
params:
  # Model hyperparameters
  time_slice: 16
  use_lstm: True
  lstm_hidden: 256
  lstm_layers: 4
  mlp_layers: 1
  mlp_hidden: 32
  scales: 1
  n_chan: 128
  kernel_size: 3
  teacher_forcing: False
  res_scale: 1
  res_layers: 16
  interpolation: area
  # Optimization hyperparameters
  factor: 0.6
  step_size: 50
  loss: l1
  lr: 0.0005
  weight_decay: 0.0001