_target_: datamodule.h5_datamodule.HDF5DatamoduleSlide
name: h5_datamodule_slide
train_path: /home/mila/o/oussama.boussif/pde_oned/data/CE_train_E1.h5
val_path: /home/mila/o/oussama.boussif/pde_oned/data/CE_valid_E1.h5
test_path: /home/mila/o/oussama.boussif/pde_oned/data/CE_test_E1.h5
nt_train: 250
nx_train: 50
nt_val: 250
nx_val: 50
nt_test: 250
nx_test: 50
time_slice: 25

num_workers: 0
batch_size: 32