_target_: datamodule.h5_datamodule_2d.HDF5Datamodule_2d
name: h5_datamodule_2d
train_path: /home/mila/o/oussama.boussif/scratch/pdeone/data/B1/burgers_train_B1_64.h5
val_path: /home/mila/o/oussama.boussif/scratch/pdeone/data/B1/burgers_test_B1_64.h5
test_path: /home/mila/o/oussama.boussif/scratch/pdeone/data/B1/burgers_test_B1_64.h5
nt_train: 50
res_train: 64
nt_val: 50
res_val: 64
nt_test: 50
res_test: 64

num_workers: 3
batch_size: 32