_target_: datamodule.h5_datamodule.PDEDatamodule
name: pde_datamodule
train_path: /home/mila/o/oussama.boussif/MP-Neural-PDE-Solvers/data/CE_train_E3.h5
val_path: /home/mila/o/oussama.boussif/MP-Neural-PDE-Solvers/data/CE_valid_E3.h5
test_path: /home/mila/o/oussama.boussif/MP-Neural-PDE-Solvers/data/CE_test_E3.h5
pde: CE
base_resolution: [250,50]

num_workers: 0
batch_size: 32